[OPENAI]
AZURE_OPENAI_KEY = "db9d4f4943224431872f6872499ac0b4"
AZURE_OPENAI_ENDPOINT = "https://sanskrutishivanshishubham.openai.azure.com/"
AZURE_LOCATION = "canadaeast"

[PINECONE]
PINECONE_API_KEY = "a3483db7-6854-46f0-a34d-6aa245f3d991"

[LANGSMITH]
LANGSMITH_API_KEY = "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"
LANGCHAIN_PROJECT = "first-deployment-llmops"